# Generated by Django 3.0.1 on 2019-12-19 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('falow_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(db_column='description', max_length=5000, verbose_name='Postagem')),
                ('comments_count', models.IntegerField(blank=True, db_column='comments_count', default=0, null=True, verbose_name='Número de comentários')),
                ('likes_count', models.IntegerField(blank=True, db_column='likes_count', default=0, null=True, verbose_name='Número de curtidas')),
                ('profile', models.ForeignKey(db_column='profile', on_delete=django.db.models.deletion.CASCADE, to='falow_app.Profile', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Postagem',
                'verbose_name_plural': 'Postagens',
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(blank=True, db_column='post', null=True, on_delete=django.db.models.deletion.CASCADE, to='falow_app.Post', verbose_name='Postagem')),
                ('user', models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Curtida',
                'verbose_name_plural': 'Curtidas',
                'db_table': 'like',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(db_column='description', max_length=5000, verbose_name='Comentário')),
                ('post', models.ForeignKey(blank=True, db_column='post', null=True, on_delete=django.db.models.deletion.CASCADE, to='falow_app.Post', verbose_name='Postagem')),
                ('user', models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'db_table': 'comment',
            },
        ),
    ]
